import "./globals.css"
import { Josefin_Sans, Montserrat } from "next/font/google"

const josefinSans = Josefin_Sans({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-josefin-sans",
})

const montserrat = Montserrat({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-montserrat",
})

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body
				className={`${josefinSans.variable} ${montserrat.variable} bg-primary-dark font-body text-primary-title`}
			>
				{children}
			</body>
		</html>
	)
}
